/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dom;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author mirenordonezdearce
 */
public class Interfaz extends javax.swing.JFrame {
    //Creo un objeto tipo DOM
    DOM gesDOM = new DOM();
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salidaTxt = new javax.swing.JTextArea();
        btnMostrarDom = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelAnno = new javax.swing.JLabel();
        jTextFieldAnno = new javax.swing.JTextField();
        btnAnnadir = new javax.swing.JButton();
        btnGuardarDoc = new javax.swing.JButton();
        jLabelTituloNuevo = new javax.swing.JLabel();
        jLabelTituloAntiguo = new javax.swing.JLabel();
        jTextFieldTituloAntiguo = new javax.swing.JTextField();
        jTextFieldTituloNuevo = new javax.swing.JTextField();
        btnModificarTitulo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        abrirDOM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salidaTxt.setEditable(false);
        salidaTxt.setColumns(20);
        salidaTxt.setRows(5);
        jScrollPane1.setViewportView(salidaTxt);

        btnMostrarDom.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnMostrarDom.setText("Mostrar Dom");
        btnMostrarDom.setEnabled(false);
        btnMostrarDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDomActionPerformed(evt);
            }
        });

        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Título:");

        jTextFieldTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jLabelAutor.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutor.setText("Autor:");

        jTextFieldAutor.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jLabelAnno.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelAnno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnno.setText("Publicado en:");

        jTextFieldAnno.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        btnAnnadir.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnAnnadir.setText("Añadir");
        btnAnnadir.setEnabled(false);
        btnAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnadirActionPerformed(evt);
            }
        });

        btnGuardarDoc.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnGuardarDoc.setText("Guardar DOM como fichero XML");
        btnGuardarDoc.setEnabled(false);
        btnGuardarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDocActionPerformed(evt);
            }
        });

        jLabelTituloNuevo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelTituloNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloNuevo.setText("Campo nuevo:");

        jLabelTituloAntiguo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelTituloAntiguo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAntiguo.setText("Campo antiguo:");

        jTextFieldTituloAntiguo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jTextFieldTituloNuevo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        btnModificarTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnModificarTitulo.setText("Modificar campo");
        btnModificarTitulo.setEnabled(false);
        btnModificarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTituloActionPerformed(evt);
            }
        });

        Menu.setText("Menu");

        abrirDOM.setText("Abrir Dom");
        abrirDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirDOMActionPerformed(evt);
            }
        });
        Menu.add(abrirDOM);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAutor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardarDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTituloNuevo)
                                    .addComponent(jTextFieldTituloAntiguo)))
                            .addComponent(btnModificarTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnMostrarDom)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarDom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAnnadir))
                            .addComponent(jLabelAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarDoc)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloAntiguo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTituloAntiguo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTituloNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarTitulo)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirDOMActionPerformed
       //Selecciona un fichero 
       File fichero = seleccionarFichero();
       if (fichero == null) {
           lblInfo.setText("Debes elegir un fichero");
           btnMostrarDom.setEnabled(false);
           btnAnnadir.setEnabled(false);
           btnGuardarDoc.setEnabled(false);
           btnModificarTitulo.setEnabled(false);
       }
       else {
           lblInfo.setText("¡DOM creado!");
           btnMostrarDom.setEnabled(true);
           btnAnnadir.setEnabled(true);
           btnGuardarDoc.setEnabled(true);
           btnModificarTitulo.setEnabled(true);
           gesDOM.abrir_XML_DOM(fichero);
       }
       
    }//GEN-LAST:event_abrirDOMActionPerformed

    private void btnMostrarDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDomActionPerformed
        //Muestra el DOM a partir de un XML
        try {
            salidaTxt.setText(gesDOM.recorrerDOMyMostrar());
        } catch (Exception e) {
            lblInfo.setText("Ha ocurrido un error al mostrar el DOM");
        }
        
    }//GEN-LAST:event_btnMostrarDomActionPerformed

    private void btnAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnadirActionPerformed
        //Añade nueva info al DOM
        try {
            gesDOM.annadirDOM(jTextFieldTitulo.getText(), jTextFieldAutor.getText(), jTextFieldAnno.getText());
            lblInfo.setText("Añadido correctamente");
        } catch (Exception e) {
            lblInfo.setText("Ha ocurrido un error al añadir");
        }
        
        
    }//GEN-LAST:event_btnAnnadirActionPerformed

    private void btnGuardarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDocActionPerformed
        //Guarda un nuevo archivo con los añadidos.
        try {
            gesDOM.guardarDOMcomoFile();
            lblInfo.setText("Fichero guardado correctamente");
        } catch (Exception e) {
            lblInfo.setText("Error al guardar el fichero");
        }
    }//GEN-LAST:event_btnGuardarDocActionPerformed

    private void btnModificarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTituloActionPerformed
        try {
            gesDOM.modificarDOM(jTextFieldTituloAntiguo.getText(), jTextFieldTituloNuevo.getText());
            lblInfo.setText("Modificado correctamente");
        } catch (Exception e){
            lblInfo.setText("Ha ocurrido un error al modificar");
        }
    }//GEN-LAST:event_btnModificarTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem abrirDOM;
    private javax.swing.JButton btnAnnadir;
    private javax.swing.JButton btnGuardarDoc;
    private javax.swing.JButton btnModificarTitulo;
    private javax.swing.JButton btnMostrarDom;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloAntiguo;
    private javax.swing.JLabel jLabelTituloNuevo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAnno;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldTituloAntiguo;
    private javax.swing.JTextField jTextFieldTituloNuevo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTextArea salidaTxt;
    // End of variables declaration//GEN-END:variables

    private File seleccionarFichero() {
        File fichero = null;

        JFileChooser archivo = new JFileChooser();
        archivo.setMultiSelectionEnabled(false);
        archivo.setDialogType(JFileChooser.OPEN_DIALOG);

        int archivoElegido = archivo.showOpenDialog(this);

        if (archivoElegido == JFileChooser.APPROVE_OPTION) {
            fichero = archivo.getSelectedFile();
        }
        return fichero;
    }
    
}
