/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DomSaxJaxB;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author mirenordonezdearce
 */
public class Interfaz extends javax.swing.JFrame {
    //Creo un objeto tipo DOM, tipo SAX y tipo JAXB
    DOM gesDOM = new DOM();
    SAX gesSAX = new SAX();
    JAXB gesJAXB = new JAXB();
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salidaTxt = new javax.swing.JTextArea();
        btnMostrarDOM = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelAnno = new javax.swing.JLabel();
        jTextFieldAnno = new javax.swing.JTextField();
        btnAnnadir = new javax.swing.JButton();
        btnGuardarDoc = new javax.swing.JButton();
        jLabelCampoNuevo = new javax.swing.JLabel();
        jLabelCampoAntiguo = new javax.swing.JLabel();
        jTextFieldCampoAntiguo = new javax.swing.JTextField();
        jTextFieldCampoNuevo = new javax.swing.JTextField();
        btnModificarCampo = new javax.swing.JButton();
        btnMostrarSAX = new javax.swing.JButton();
        btnMostrarJAXB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        abrirDOM = new javax.swing.JMenuItem();
        abrirSAX = new javax.swing.JMenuItem();
        abrirJAXB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salidaTxt.setEditable(false);
        salidaTxt.setColumns(20);
        salidaTxt.setLineWrap(true);
        salidaTxt.setRows(5);
        salidaTxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(salidaTxt);

        btnMostrarDOM.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnMostrarDOM.setText("Mostrar Dom");
        btnMostrarDOM.setEnabled(false);
        btnMostrarDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDOMActionPerformed(evt);
            }
        });

        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Título:");

        jTextFieldTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jLabelAutor.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutor.setText("Autor:");

        jTextFieldAutor.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jLabelAnno.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelAnno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnno.setText("Publicado en:");

        jTextFieldAnno.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        btnAnnadir.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnAnnadir.setText("Añadir");
        btnAnnadir.setEnabled(false);
        btnAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnadirActionPerformed(evt);
            }
        });

        btnGuardarDoc.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnGuardarDoc.setText("Guardar DOM como fichero XML");
        btnGuardarDoc.setEnabled(false);
        btnGuardarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDocActionPerformed(evt);
            }
        });

        jLabelCampoNuevo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelCampoNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCampoNuevo.setText("Campo nuevo:");

        jLabelCampoAntiguo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelCampoAntiguo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCampoAntiguo.setText("Campo antiguo:");

        jTextFieldCampoAntiguo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jTextFieldCampoNuevo.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        btnModificarCampo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        btnModificarCampo.setText("Modificar campo");
        btnModificarCampo.setEnabled(false);
        btnModificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCampoActionPerformed(evt);
            }
        });

        btnMostrarSAX.setText("Mostrar SAX");
        btnMostrarSAX.setEnabled(false);
        btnMostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSAXActionPerformed(evt);
            }
        });

        btnMostrarJAXB.setText("Mostrar JAXB");
        btnMostrarJAXB.setEnabled(false);
        btnMostrarJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarJAXBActionPerformed(evt);
            }
        });

        Menu.setText("Menu");

        abrirDOM.setText("Abrir DOM");
        abrirDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirDOMActionPerformed(evt);
            }
        });
        Menu.add(abrirDOM);

        abrirSAX.setText("Abrir SAX");
        abrirSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirSAXActionPerformed(evt);
            }
        });
        Menu.add(abrirSAX);

        abrirJAXB.setText("Abrir JAXB");
        abrirJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirJAXBActionPerformed(evt);
            }
        });
        Menu.add(abrirJAXB);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardarDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCampoAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCampoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCampoNuevo)
                            .addComponent(jTextFieldCampoAntiguo)))
                    .addComponent(btnModificarCampo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnMostrarDOM)
                .addGap(97, 97, 97)
                .addComponent(btnMostrarSAX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarJAXB)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarDOM)
                    .addComponent(btnMostrarSAX)
                    .addComponent(btnMostrarJAXB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAnnadir))
                            .addComponent(jLabelAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarDoc)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCampoAntiguo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCampoAntiguo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCampoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCampoNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarCampo)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirDOMActionPerformed
       //Selecciona un fichero 
       File fichero = seleccionarFichero();
       if (fichero == null) {
           lblInfo.setText("Debes elegir un fichero");
           btnMostrarDOM.setEnabled(false);
           btnAnnadir.setEnabled(false);
           btnGuardarDoc.setEnabled(false);
           btnModificarCampo.setEnabled(false);
           btnMostrarSAX.setEnabled(false);
           btnMostrarJAXB.setEnabled(false);
       }
       else {
           lblInfo.setText("¡DOM creado!");
           btnMostrarDOM.setEnabled(true);
           btnAnnadir.setEnabled(true);
           btnGuardarDoc.setEnabled(true);
           btnModificarCampo.setEnabled(true);
           gesDOM.abrir_XML_DOM(fichero);
           btnMostrarSAX.setEnabled(false);
           btnMostrarJAXB.setEnabled(false);
       }
       
    }//GEN-LAST:event_abrirDOMActionPerformed

    private void btnMostrarDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDOMActionPerformed
        //Muestra el DOM a partir de un XML
        try {
            salidaTxt.setText(gesDOM.recorrerDOMyMostrar());
        } catch (Exception e) {
            lblInfo.setText("Ha ocurrido un error al mostrar el DOM");
        }
        
    }//GEN-LAST:event_btnMostrarDOMActionPerformed

    private void btnAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnadirActionPerformed
        //Añade nueva info al DOM
        try {
            gesDOM.annadirDOM(jTextFieldTitulo.getText(), jTextFieldAutor.getText(), jTextFieldAnno.getText());
            lblInfo.setText("Añadido correctamente");
        } catch (Exception e) {
            lblInfo.setText("Ha ocurrido un error al añadir");
        }
        
        
    }//GEN-LAST:event_btnAnnadirActionPerformed

    private void btnGuardarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDocActionPerformed
        //Guarda un nuevo archivo con los añadidos.
        try {
            //gesDOM.guardarDOMcomoFile();
            lblInfo.setText("Fichero guardado correctamente");
        } catch (Exception e) {
            lblInfo.setText("Error al guardar el fichero");
        }
    }//GEN-LAST:event_btnGuardarDocActionPerformed

    private void btnModificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCampoActionPerformed
        try {
            gesDOM.modificarDOM(jTextFieldCampoAntiguo.getText(), jTextFieldCampoNuevo.getText());
            lblInfo.setText("Modificado correctamente");
        } catch (Exception e){
            lblInfo.setText("Ha ocurrido un error al modificar");
        }
    }//GEN-LAST:event_btnModificarCampoActionPerformed

    
    //SAX
    private void abrirSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirSAXActionPerformed
        File fichero = seleccionarFichero();
        if (fichero == null) {
           lblInfo.setText("Debes elegir un fichero");
           btnMostrarDOM.setEnabled(false);
           btnAnnadir.setEnabled(false);
           btnGuardarDoc.setEnabled(false);
           btnModificarCampo.setEnabled(false);
           btnMostrarSAX.setEnabled(false);
           btnMostrarJAXB.setEnabled(false);
       }
       else {
           lblInfo.setText("¡SAX listo!");
           btnMostrarDOM.setEnabled(false);
           btnAnnadir.setEnabled(false);
           btnGuardarDoc.setEnabled(false);
           btnModificarCampo.setEnabled(false);
           btnMostrarSAX.setEnabled(true);
           gesSAX.abrir_XML_SAX(fichero);
           btnMostrarJAXB.setEnabled(false);
       }
    }//GEN-LAST:event_abrirSAXActionPerformed

    private void btnMostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSAXActionPerformed
        //Muestra el SAX a partir de un XML
        try {
            salidaTxt.setText( gesSAX.recorrerSAX());
            //salidaTxt.setText(gesSAX.recorrerSAX());
        } catch (Exception e) {
            lblInfo.setText("Ha ocurrido un error al mostrar el SAX");
        }
    }//GEN-LAST:event_btnMostrarSAXActionPerformed

    private void abrirJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirJAXBActionPerformed
        File fichero = seleccionarFichero();
        if (fichero == null) {
           lblInfo.setText("Debes elegir un fichero");
           btnMostrarDOM.setEnabled(false);
           btnAnnadir.setEnabled(false);
           btnGuardarDoc.setEnabled(false);
           btnModificarCampo.setEnabled(false);
           btnMostrarSAX.setEnabled(false);
           btnMostrarJAXB.setEnabled(false);
       }
       else {
           lblInfo.setText("¡JAXB listo!");
           btnMostrarDOM.setEnabled(false);
           btnAnnadir.setEnabled(false);
           btnGuardarDoc.setEnabled(false);
           btnModificarCampo.setEnabled(false);
           btnMostrarSAX.setEnabled(false);
           btnMostrarJAXB.setEnabled(true);
           gesJAXB.abrir_XML_JAXB(fichero);
       }
    }//GEN-LAST:event_abrirJAXBActionPerformed

    private void btnMostrarJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarJAXBActionPerformed
        //Muestra el JAXB a partir de un XML
        try {
            salidaTxt.setText(gesJAXB.recorrerJAXB());
        } catch (Exception e) {
            lblInfo.setText("Ha ocurrido un error al mostrar el JAXB");
        }
    }//GEN-LAST:event_btnMostrarJAXBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem abrirDOM;
    private javax.swing.JMenuItem abrirJAXB;
    private javax.swing.JMenuItem abrirSAX;
    private javax.swing.JButton btnAnnadir;
    private javax.swing.JButton btnGuardarDoc;
    private javax.swing.JButton btnModificarCampo;
    private javax.swing.JButton btnMostrarDOM;
    private javax.swing.JButton btnMostrarJAXB;
    private javax.swing.JButton btnMostrarSAX;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelCampoAntiguo;
    private javax.swing.JLabel jLabelCampoNuevo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAnno;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCampoAntiguo;
    private javax.swing.JTextField jTextFieldCampoNuevo;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTextArea salidaTxt;
    // End of variables declaration//GEN-END:variables

    private File seleccionarFichero() {
        File fichero = null;

        JFileChooser archivo = new JFileChooser();
        archivo.setMultiSelectionEnabled(false);
        archivo.setDialogType(JFileChooser.OPEN_DIALOG);

        int archivoElegido = archivo.showOpenDialog(this);

        if (archivoElegido == JFileChooser.APPROVE_OPTION) {
            fichero = archivo.getSelectedFile();
        }
        return fichero;
    }
    
}
